### ISSUE TITLE
12: View Profiles

### ISSUE THREAD

**Issue by palmpilot71** [CMPUT301F15T05/cuddly-quack#11]
1. Add the view & activity (might be able to reuse the view profile)
2. Implement the required controllers and models to produce this functionality

Note: Should display the add friend button if not currently friends and shouldn't display the add friend button if are already friends

Leave a comment if you are working on one of the above and a comment when it is completed.
Don't forget to use TDD!

**Comment by nettapper** [comment]
Done this with Daniel.
