### ISSUE TITLE
16: Notify

### ISSUE THREAD

**Issue by palmpilot71** [CMPUT301F15T05/cuddly-quack#15]
1. Implement the required controllers and models to produce this functionality

Note: This is when either a popup occurs or there is a pending notification before launching the app

Leave a comment if you are working on one of the above and a comment when it is completed.
Don't forget to use TDD!

**Comment by adrianomarini** [comment]
Notifications are implemented. NotificationManager uses AlertDialog to warn of new followers and pending trades that are in the active trades category.
