### ISSUE TITLE
A LOT of tests fail ATM

### ISSUE THREAD

**Issue by nettapper** [CMPUT301F15T05/cuddly-quack#20]
Fix The Tests By Commenting lines out, or changing the way they work to make our TDD easier to do!

**Comment by adrianomarini** [comment]
Fixed TradeTest, ConfigurationTest, and Inventory test tonight.

**Comment by nettapper** [comment]
Only a few are acting up, I really don't know what is going on with the UserSingleton but the other failing test cases are from Trade and Pictures (two things we have yet to implement).
