### ISSUE TITLE
3: View Item

### ISSUE THREAD

**Issue by palmpilot71** [CMPUT301F15T05/cuddly-quack#4]
1. Create the View Item Layout and Activity
2. Details of an item should be displayed when clicked
3. Implement the required controllers and models to produce this functionality

Leave a comment if you are working on one of the above and a comment when it is completed.
Don't forget to use TDD!

**Comment by nettapper** [comment]
Did part 1 & 2 with Daniel

**Comment by GarryBullock** [comment]
Viewing inventory items has been implemented...
