### ISSUE TITLE
9: Add Friend

### ISSUE THREAD

**Issue by palmpilot71** [CMPUT301F15T05/cuddly-quack#8]
1. Add view and activity (if needed) so friends can be added after searching for them
2. Implement the required controllers and models to produce this functionality

Note: A friend request is generated so the other person has the option to accept or decline a request

Leave a comment if you are working on one of the above and a comment when it is completed.
Don't forget to use TDD!

**Comment by nettapper** [comment]
Almost all done, just need to send a request notification.

**Comment by palmpilot71** [comment]
Request notification sends now, but I can't get them to stop popping up on next login after being read.

**Comment by adrianomarini** [comment]
Fixed issue that @palmpilot71 described above. Issue still exists because a friend can be added multiple times.

**Comment by adrianomarini** [comment]
You can no longer add friends twice.
